sudo: false
language: node_js
env:
  - DEV_DB_TEST=mongodb://localhost:27017/TestMyBrandDB
node_js:
  - "stable"
services:
  - mongodb
cache:
  npm: false
notifications:
  email: false
script:
  - npm ci
  - npm  test
  - npm run coverage
after_success:
  - npm run coveralls